# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serial.ui'
#
# Created: Thu May 19 16:26:54 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(707, 689)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.commandLinkButton_serailopen = QtGui.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_serailopen.setGeometry(QtCore.QRect(190, 30, 81, 41))
        self.commandLinkButton_serailopen.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commandLinkButton_serailopen.setObjectName(_fromUtf8("commandLinkButton_serailopen"))
        self.comboBox_serialport = QtGui.QComboBox(self.centralwidget)
        self.comboBox_serialport.setGeometry(QtCore.QRect(10, 30, 121, 41))
        self.comboBox_serialport.setObjectName(_fromUtf8("comboBox_serialport"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 160, 291, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.comboBox_serialbauds = QtGui.QComboBox(self.centralwidget)
        self.comboBox_serialbauds.setGeometry(QtCore.QRect(10, 100, 121, 41))
        self.comboBox_serialbauds.setObjectName(_fromUtf8("comboBox_serialbauds"))
        self.comboBox_serialbauds.addItem(_fromUtf8(""))
        self.comboBox_serialbauds.addItem(_fromUtf8(""))
        self.comboBox_serialbauds.addItem(_fromUtf8(""))
        self.comboBox_serialbauds.addItem(_fromUtf8(""))
        self.comboBox_serialbauds.addItem(_fromUtf8(""))
        self.comboBox_serialbauds.addItem(_fromUtf8(""))
        self.comboBox_serialbauds.addItem(_fromUtf8(""))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 61, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton_stop = QtGui.QPushButton(self.centralwidget)
        self.pushButton_stop.setEnabled(False)
        self.pushButton_stop.setGeometry(QtCore.QRect(140, 100, 101, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon/cancel-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_stop.setIcon(icon)
        self.pushButton_stop.setObjectName(_fromUtf8("pushButton_stop"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(290, 0, 20, 631))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 20, 91, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(320, 260, 91, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 91, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(310, 480, 391, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(310, 500, 111, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 580, 91, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pushButton_send_rawcmd = QtGui.QPushButton(self.centralwidget)
        self.pushButton_send_rawcmd.setGeometry(QtCore.QRect(230, 600, 61, 31))
        self.pushButton_send_rawcmd.setObjectName(_fromUtf8("pushButton_send_rawcmd"))
        self.textEdit_sendcmd = QtGui.QTextEdit(self.centralwidget)
        self.textEdit_sendcmd.setGeometry(QtCore.QRect(10, 600, 211, 31))
        self.textEdit_sendcmd.setObjectName(_fromUtf8("textEdit_sendcmd"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(610, 20, 85, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(610, 260, 85, 27))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(610, 500, 85, 27))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.textEdit_debugmessage = QtGui.QTextEdit(self.centralwidget)
        self.textEdit_debugmessage.setEnabled(False)
        self.textEdit_debugmessage.setGeometry(QtCore.QRect(310, 530, 381, 101))
        self.textEdit_debugmessage.setObjectName(_fromUtf8("textEdit_debugmessage"))
        self.textEdit_recivemessage = QtGui.QTextEdit(self.centralwidget)
        self.textEdit_recivemessage.setEnabled(True)
        self.textEdit_recivemessage.setGeometry(QtCore.QRect(310, 290, 381, 181))
        self.textEdit_recivemessage.setObjectName(_fromUtf8("textEdit_recivemessage"))
        self.textEdit_sendmessage = QtGui.QTextEdit(self.centralwidget)
        self.textEdit_sendmessage.setEnabled(True)
        self.textEdit_sendmessage.setGeometry(QtCore.QRect(310, 50, 381, 181))
        self.textEdit_sendmessage.setObjectName(_fromUtf8("textEdit_sendmessage"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 560, 291, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.formLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 300, 261, 111))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_9 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_10)
        self.comboBox_d001_value = QtGui.QComboBox(self.formLayoutWidget)
        self.comboBox_d001_value.setObjectName(_fromUtf8("comboBox_d001_value"))
        self.comboBox_d001_value.addItem(_fromUtf8(""))
        self.comboBox_d001_value.addItem(_fromUtf8(""))
        self.comboBox_d001_value.addItem(_fromUtf8(""))
        self.comboBox_d001_value.addItem(_fromUtf8(""))
        self.comboBox_d001_value.addItem(_fromUtf8(""))
        self.comboBox_d001_value.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBox_d001_value)
        self.comboBox_d005_value = QtGui.QComboBox(self.formLayoutWidget)
        self.comboBox_d005_value.setObjectName(_fromUtf8("comboBox_d005_value"))
        self.comboBox_d005_value.addItem(_fromUtf8(""))
        self.comboBox_d005_value.addItem(_fromUtf8(""))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboBox_d005_value)
        self.comboBox_d002_value = QtGui.QComboBox(self.formLayoutWidget)
        self.comboBox_d002_value.setObjectName(_fromUtf8("comboBox_d002_value"))
        self.comboBox_d002_value.addItem(_fromUtf8(""))
        self.comboBox_d002_value.addItem(_fromUtf8(""))
        self.comboBox_d002_value.addItem(_fromUtf8(""))
        self.comboBox_d002_value.addItem(_fromUtf8(""))
        self.comboBox_d002_value.addItem(_fromUtf8(""))
        self.comboBox_d002_value.addItem(_fromUtf8(""))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBox_d002_value)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_8)
        self.pushButton_serialrefresh = QtGui.QPushButton(self.centralwidget)
        self.pushButton_serialrefresh.setGeometry(QtCore.QRect(140, 30, 41, 41))
        self.pushButton_serialrefresh.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icon/refresh-page-option.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_serialrefresh.setIcon(icon1)
        self.pushButton_serialrefresh.setObjectName(_fromUtf8("pushButton_serialrefresh"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 210, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.comboBox_choosepath = QtGui.QComboBox(self.centralwidget)
        self.comboBox_choosepath.setGeometry(QtCore.QRect(40, 210, 71, 25))
        self.comboBox_choosepath.setObjectName(_fromUtf8("comboBox_choosepath"))
        self.comboBox_choosepath.addItem(_fromUtf8(""))
        self.comboBox_choosepath.addItem(_fromUtf8(""))
        self.comboBox_choosepath.addItem(_fromUtf8(""))
        self.comboBox_choosepath.addItem(_fromUtf8(""))
        self.comboBox_choosepath.addItem(_fromUtf8(""))
        self.comboBox_choosepath.addItem(_fromUtf8(""))
        self.comboBox_path2stop = QtGui.QComboBox(self.centralwidget)
        self.comboBox_path2stop.setGeometry(QtCore.QRect(110, 210, 71, 25))
        self.comboBox_path2stop.setObjectName(_fromUtf8("comboBox_path2stop"))
        self.comboBox_path2stop.addItem(_fromUtf8(""))
        self.comboBox_path2stop.addItem(_fromUtf8(""))
        self.comboBox_path2stop.addItem(_fromUtf8(""))
        self.textEdit_currentcmd = QtGui.QTextEdit(self.centralwidget)
        self.textEdit_currentcmd.setGeometry(QtCore.QRect(10, 530, 211, 31))
        self.textEdit_currentcmd.setObjectName(_fromUtf8("textEdit_currentcmd"))
        self.pushButton_addpath = QtGui.QPushButton(self.centralwidget)
        self.pushButton_addpath.setGeometry(QtCore.QRect(190, 210, 85, 27))
        self.pushButton_addpath.setObjectName(_fromUtf8("pushButton_addpath"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 510, 91, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.pushButton_send_currentcmd = QtGui.QPushButton(self.centralwidget)
        self.pushButton_send_currentcmd.setGeometry(QtCore.QRect(230, 530, 61, 31))
        self.pushButton_send_currentcmd.setObjectName(_fromUtf8("pushButton_send_currentcmd"))
        self.pushButton_reset_funbtn = QtGui.QPushButton(self.centralwidget)
        self.pushButton_reset_funbtn.setGeometry(QtCore.QRect(190, 180, 85, 27))
        self.pushButton_reset_funbtn.setObjectName(_fromUtf8("pushButton_reset_funbtn"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 411, 261, 95))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_13 = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_13)
        self.pushButton_batterystate = QtGui.QPushButton(self.formLayoutWidget_2)
        self.pushButton_batterystate.setObjectName(_fromUtf8("pushButton_batterystate"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.pushButton_batterystate)
        self.lineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.lineEdit_2 = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.pushButton_lastcardstate = QtGui.QPushButton(self.formLayoutWidget_2)
        self.pushButton_lastcardstate.setObjectName(_fromUtf8("pushButton_lastcardstate"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.pushButton_lastcardstate)
        self.pushButton_runstate = QtGui.QPushButton(self.formLayoutWidget_2)
        self.pushButton_runstate.setObjectName(_fromUtf8("pushButton_runstate"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.pushButton_runstate)
        self.pushButton_addrotation = QtGui.QPushButton(self.centralwidget)
        self.pushButton_addrotation.setGeometry(QtCore.QRect(190, 250, 85, 27))
        self.pushButton_addrotation.setObjectName(_fromUtf8("pushButton_addrotation"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(40, 250, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.comboBox_rotation = QtGui.QComboBox(self.centralwidget)
        self.comboBox_rotation.setGeometry(QtCore.QRect(110, 250, 71, 25))
        self.comboBox_rotation.setObjectName(_fromUtf8("comboBox_rotation"))
        self.comboBox_rotation.addItem(_fromUtf8(""))
        self.comboBox_rotation.addItem(_fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 707, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout_AutoCar = QtGui.QAction(MainWindow)
        self.actionAbout_AutoCar.setObjectName(_fromUtf8("actionAbout_AutoCar"))
        self.actionRestart_2 = QtGui.QAction(MainWindow)
        self.actionRestart_2.setObjectName(_fromUtf8("actionRestart_2"))
        self.actionDocument = QtGui.QAction(MainWindow)
        self.actionDocument.setObjectName(_fromUtf8("actionDocument"))
        self.action_checkupdate = QtGui.QAction(MainWindow)
        self.action_checkupdate.setObjectName(_fromUtf8("action_checkupdate"))
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionDocument)
        self.menuHelp.addAction(self.action_checkupdate)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_AutoCar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.textEdit_sendmessage.clear)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.textEdit_recivemessage.clear)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), self.textEdit_debugmessage.clear)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox_serialbauds, self.commandLinkButton_serailopen)
        MainWindow.setTabOrder(self.commandLinkButton_serailopen, self.comboBox_serialport)
        MainWindow.setTabOrder(self.comboBox_serialport, self.pushButton_stop)
        MainWindow.setTabOrder(self.pushButton_stop, self.pushButton_send_rawcmd)
        MainWindow.setTabOrder(self.pushButton_send_rawcmd, self.textEdit_sendcmd)
        MainWindow.setTabOrder(self.textEdit_sendcmd, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.textEdit_debugmessage)
        MainWindow.setTabOrder(self.textEdit_debugmessage, self.textEdit_recivemessage)
        MainWindow.setTabOrder(self.textEdit_recivemessage, self.textEdit_sendmessage)
        MainWindow.setTabOrder(self.textEdit_sendmessage, self.comboBox_d001_value)
        MainWindow.setTabOrder(self.comboBox_d001_value, self.comboBox_d005_value)
        MainWindow.setTabOrder(self.comboBox_d005_value, self.pushButton_serialrefresh)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "AutoCar Application_V1.0", None))
        self.commandLinkButton_serailopen.setText(_translate("MainWindow", "Open", None))
        self.comboBox_serialbauds.setItemText(0, _translate("MainWindow", "9600", None))
        self.comboBox_serialbauds.setItemText(1, _translate("MainWindow", "4800", None))
        self.comboBox_serialbauds.setItemText(2, _translate("MainWindow", "14400", None))
        self.comboBox_serialbauds.setItemText(3, _translate("MainWindow", "19200", None))
        self.comboBox_serialbauds.setItemText(4, _translate("MainWindow", "38400", None))
        self.comboBox_serialbauds.setItemText(5, _translate("MainWindow", "57600", None))
        self.comboBox_serialbauds.setItemText(6, _translate("MainWindow", "115200", None))
        self.label.setText(_translate("MainWindow", "Port Select", None))
        self.label_2.setText(_translate("MainWindow", "Bauds", None))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop", None))
        self.label_3.setText(_translate("MainWindow", "Send message", None))
        self.label_4.setText(_translate("MainWindow", "Recive message", None))
        self.label_5.setText(_translate("MainWindow", "Funtion Botton", None))
        self.label_6.setText(_translate("MainWindow", "Debug Message", None))
        self.label_7.setText(_translate("MainWindow", "Send raw cmd", None))
        self.pushButton_send_rawcmd.setText(_translate("MainWindow", "Send", None))
        self.pushButton.setText(_translate("MainWindow", "Clear", None))
        self.pushButton_2.setText(_translate("MainWindow", "Clear", None))
        self.pushButton_3.setText(_translate("MainWindow", "Clear", None))
        self.label_9.setText(_translate("MainWindow", "速度(0->OFF)    ", None))
        self.label_10.setText(_translate("MainWindow", "分支", None))
        self.comboBox_d001_value.setItemText(0, _translate("MainWindow", "3", None))
        self.comboBox_d001_value.setItemText(1, _translate("MainWindow", "0", None))
        self.comboBox_d001_value.setItemText(2, _translate("MainWindow", "1", None))
        self.comboBox_d001_value.setItemText(3, _translate("MainWindow", "5", None))
        self.comboBox_d001_value.setItemText(4, _translate("MainWindow", "7", None))
        self.comboBox_d001_value.setItemText(5, _translate("MainWindow", "9", None))
        self.comboBox_d005_value.setItemText(0, _translate("MainWindow", "左", None))
        self.comboBox_d005_value.setItemText(1, _translate("MainWindow", "右", None))
        self.comboBox_d002_value.setItemText(0, _translate("MainWindow", "0", None))
        self.comboBox_d002_value.setItemText(1, _translate("MainWindow", "1", None))
        self.comboBox_d002_value.setItemText(2, _translate("MainWindow", "3", None))
        self.comboBox_d002_value.setItemText(3, _translate("MainWindow", "5", None))
        self.comboBox_d002_value.setItemText(4, _translate("MainWindow", "7", None))
        self.comboBox_d002_value.setItemText(5, _translate("MainWindow", "9", None))
        self.label_8.setText(_translate("MainWindow", "聲音(0->OFF)    ", None))
        self.label_11.setText(_translate("MainWindow", "經過", None))
        self.comboBox_choosepath.setItemText(0, _translate("MainWindow", "A001", None))
        self.comboBox_choosepath.setItemText(1, _translate("MainWindow", "A002", None))
        self.comboBox_choosepath.setItemText(2, _translate("MainWindow", "A003", None))
        self.comboBox_choosepath.setItemText(3, _translate("MainWindow", "A004", None))
        self.comboBox_choosepath.setItemText(4, _translate("MainWindow", "A005", None))
        self.comboBox_choosepath.setItemText(5, _translate("MainWindow", "A006", None))
        self.comboBox_path2stop.setItemText(0, _translate("MainWindow", "不停", None))
        self.comboBox_path2stop.setItemText(1, _translate("MainWindow", "停", None))
        self.comboBox_path2stop.setItemText(2, _translate("MainWindow", "緩停", None))
        self.textEdit_currentcmd.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.pushButton_addpath.setText(_translate("MainWindow", "Add", None))
        self.label_12.setText(_translate("MainWindow", "Current cmd", None))
        self.pushButton_send_currentcmd.setText(_translate("MainWindow", "Send", None))
        self.pushButton_reset_funbtn.setText(_translate("MainWindow", "Reset", None))
        self.label_13.setText(_translate("MainWindow", "行駛狀態", None))
        self.pushButton_batterystate.setText(_translate("MainWindow", "電量", None))
        self.pushButton_lastcardstate.setText(_translate("MainWindow", "目前位置", None))
        self.pushButton_runstate.setText(_translate("MainWindow", "目前行徑狀態", None))
        self.pushButton_addrotation.setText(_translate("MainWindow", "Add", None))
        self.label_15.setText(_translate("MainWindow", "迴轉", None))
        self.comboBox_rotation.setItemText(0, _translate("MainWindow", "右", None))
        self.comboBox_rotation.setItemText(1, _translate("MainWindow", "左", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionExit.setText(_translate("MainWindow", "exit", None))
        self.actionAbout_AutoCar.setText(_translate("MainWindow", "About  Application", None))
        self.actionRestart_2.setText(_translate("MainWindow", "restart", None))
        self.actionDocument.setText(_translate("MainWindow", "Document", None))
        self.action_checkupdate.setText(_translate("MainWindow", "檢查更新", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

